global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "restaurant-api"
    static_configs:
      - targets:
          [
            "localhost:5000",
          ]
    metrics_path: "/metrics"

  - job_name: "node-exporter"
    static_configs:
      - targets:
          [
            "localhost:9100",
          ]

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            [
              "localhost:9093",
            ]

rule_files:
  - "alert.rules.yml"
